### ISSUE TITLE
Revisar imports

### ISSUE THREAD

**Issue by lmorillas** [UnaiSuarez/TiendaVideojuegosDjango#3]
Eliminar los que no se usan (requests )

**Comment by UnaiSuarez** [comment]
¿Cúal no se está utilizando?

**Comment by lmorillas** [comment]
https://github.com/UnaiSuarez/TiendaVideojuegosDjango/blob/4a118f09c463feab7cfb9f8f8108a2d9981d5121/tienda/views.py#L10
