### ISSUE TITLE
Revisar código

### ISSUE THREAD

**Issue by lmorillas** [UnaiSuarez/TiendaVideojuegosDjango#4]
En este bloque se inicializa una variable varias veces. Seguramente no hace lo que quieres.

https://github.com/UnaiSuarez/TiendaVideojuegosDjango/blob/4a118f09c463feab7cfb9f8f8108a2d9981d5121/tienda/views.py#L182

**Comment by UnaiSuarez** [comment]
No sé cuál es la variable que se inicializa varias veces y si que hace exactamente lo que quiero que es comprobar que el código de la tarjeta sea correcto para así añadirle el saldo al usuario

**Comment by lmorillas** [comment]
`añadirSaldo`  se inicializa cada iteración del `for`

**Comment by UnaiSuarez** [comment]
se inicializa el primero, justo arriba, y ahí lo unico que hago es que compruebe que el codgio existe, en caso de que no exista se vuelve false para que no se agregue el dinero, si existe comprueba si esta habilitado ya que la tarjeta solo se puede canjear una única vez, he añadido un break para que cuando compruebe que la tarjeta existe y esta habilitda no siga con el for

**Comment by UnaiSuarez** [comment]
vale, ya lo he simplificado, he puesto que se inicialice en False asi la unica que vez que la pongo en True será si está todo correcto y así no tengo que estar poniendo todo el rato que sea False

**Comment by lmorillas** [comment]
Perfecto. Cierra las incidencias cuando estén resueltas. O en la interfaz o poniendo un mensaje en el commit, por ejemplo para esta incidencia: 

`Fixes #4` y el resto del mensaje
