### ISSUE TITLE
Login / creación de usuarios

### ISSUE THREAD

**Issue by lmorillas** [UnaiSuarez/TiendaVideojuegosDjango#5]
Mejor crear un usuario del sistema, si no el login se complicará. Ahora no funciona

**Comment by UnaiSuarez** [comment]
Utilizo el usuario del sistema, solo que le añadí nuevos campos como puede ser el salario, no sé si es a eso a lo que te refieres

**Comment by UnaiSuarez** [comment]
¿Y como que ahora no funciona?

**Comment by lmorillas** [comment]
https://github.com/UnaiSuarez/TiendaVideojuegosDjango/blob/4a118f09c463feab7cfb9f8f8108a2d9981d5121/tienda/forms.py#L9 
Aquí usas un modelo tuyo, no el de django, no?
¿Si registras un usuario, te funciona bien?

**Comment by UnaiSuarez** [comment]
Cojo el modelo que trae django y le añado nuevas tablas, pero sigue siendo el mismo modelo de usuario, sería como un extends, estuve mirando porque sabia que habria alguna manera para editar el modelo de usuario por defecto y si, si que me funciona bien, el lunes te lo enseño.
